// <auto-generated />
namespace VideoRentalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDueDatePropertyToRentals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDueDatePropertyToRentals));
        
        string IMigrationMetadata.Id
        {
            get { return "202202130008243_AddDueDatePropertyToRentals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
